const sounds=[['kick','🦖','Dino Kick','#f2b83f'],['snap','🐍','Snake Snap','#9be27b'],['meow','🐱','Cat Meow','#ffb7d8'],['whistle','🪶','Feather Whistle','#bfe2ff'],['cool','😎','Cool Pad','#d8ccff']];
let ctx,delay,feedback,wet,convolver,master,playing=false,step=0,timer;
let pattern=[[1,0,0,0,1,0,0,0],[0,0,1,0,0,0,1,0],[0,0,0,1,0,0,0,1],[0,1,0,0,0,1,0,0],[0,0,0,0,1,0,0,0]];
const $=q=>document.querySelector(q), $$=q=>Array.from(document.querySelectorAll(q));
function audio(){if(ctx)return;ctx=new(AudioContext||webkitAudioContext)();master=ctx.createGain();master.gain.value=.75;master.connect(ctx.destination);delay=ctx.createDelay(1);feedback=ctx.createGain();delay.delayTime.value=.22;feedback.gain.value=.25;delay.connect(feedback);feedback.connect(delay);delay.connect(master);convolver=ctx.createConvolver();convolver.buffer=impulse(.5);wet=ctx.createGain();wet.gain.value=.18;convolver.connect(wet);wet.connect(master)}
function impulse(sec){let b=ctx.createBuffer(2,ctx.sampleRate*sec,ctx.sampleRate);for(let c=0;c<2;c++){let d=b.getChannelData(c);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/d.length,2)}return b}
function settings(){if(!ctx)return;feedback.gain.value=+$('#echo').value/100;delay.delayTime.value=.1+(+$('#echo').value/320);wet.gain.value=+$('#space').value/100}
function gain(t,a=.01,d=.25,v=.6){let g=ctx.createGain();g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(v,t+a);g.gain.exponentialRampToValueAtTime(.001,t+a+d);return g}
function out(n){n.connect(master);n.connect(delay);n.connect(convolver)}
function ratio(){return Math.pow(2,+$('#pitch').value/12)}
function sound(id,when=0){audio();settings();let t=when||ctx.currentTime,r=ratio();if(ctx.state==='suspended')ctx.resume();
 if(id==='kick'){let o=ctx.createOscillator(),g=gain(t,.005,.35,.95);o.type='sine';o.frequency.setValueAtTime(95*r,t);o.frequency.exponentialRampToValueAtTime(38*r,t+.3);o.connect(g);out(g);o.start(t);o.stop(t+.42)}
 if(id==='snap'){let b=ctx.createBuffer(1,ctx.sampleRate*.07,ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length);let s=ctx.createBufferSource(),f=ctx.createBiquadFilter(),g=gain(t,.002,.1,.45);s.buffer=b;f.type='highpass';f.frequency.value=1200*r;s.connect(f);f.connect(g);out(g);s.start(t)}
 if(id==='meow'){let o=ctx.createOscillator(),g=gain(t,.02,.36,.35);o.type='triangle';o.frequency.setValueAtTime(520*r,t);o.frequency.exponentialRampToValueAtTime(240*r,t+.32);o.connect(g);out(g);o.start(t);o.stop(t+.45)}
 if(id==='whistle'){let o=ctx.createOscillator(),g=gain(t,.02,.38,.28);o.type='sine';o.frequency.setValueAtTime(950*r,t);o.frequency.linearRampToValueAtTime(1380*r,t+.2);o.frequency.linearRampToValueAtTime(1100*r,t+.34);o.connect(g);out(g);o.start(t);o.stop(t+.45)}
 if(id==='cool'){let o=ctx.createOscillator(),f=ctx.createBiquadFilter(),g=gain(t,.03,.5,.28);o.type='sawtooth';o.frequency.value=190*r;f.type='bandpass';f.frequency.value=760*r;f.Q.value=7;o.connect(f);f.connect(g);out(g);o.start(t);o.stop(t+.55);if(!when&&speechSynthesis){let u=new SpeechSynthesisUtterance('cool');u.rate=1.1;u.pitch=1.2;u.volume=.25;speechSynthesis.cancel();speechSynthesis.speak(u)}}
 let m=$('#roarMeter');m.style.width=Math.min(100,(parseFloat(m.style.width)||0)+18)+'%';setTimeout(()=>m.style.width='0%',180)}
function render(){pads.innerHTML=sounds.map(s=>`<button class="pad" style="background:${s[3]}" data-pad="${s[0]}"><b>${s[1]}</b><span>${s[2]}</span><small>tap to test</small></button>`).join('');stepHead.innerHTML='<span>Sound</span>'+[1,2,3,4,5,6,7,8].map(n=>`<span>${n}</span>`).join('');sequencer.innerHTML=sounds.map((s,r)=>`<div class="track"><div class="track-name">${s[1]} ${s[2]}</div>${[0,1,2,3,4,5,6,7].map(i=>`<button class="cell ${pattern[r][i]?'on':''}" data-r="${r}" data-s="${i}"></button>`).join('')}</div>`).join('')}
function refresh(){$$('.cell').forEach(c=>c.classList.toggle('on',!!pattern[c.dataset.r][c.dataset.s]))}
function beat(){let ms=60000/+bpm.value/2;$$('.cell').forEach(c=>c.classList.remove('playing'));pattern.forEach((row,r)=>{if(row[step])sound(sounds[r][0]);let c=document.querySelector(`[data-r="${r}"][data-s="${step}"]`);if(c)c.classList.add('playing')});step=(step+1)%8;timer=setTimeout(beat,ms+(step%2?+swing.value:0))}
function play(){if(playing)return;playing=true;playBtn.textContent='⏸ Playing';beat()}function stop(){playing=false;clearTimeout(timer);playBtn.textContent='▶ Play';$$('.cell').forEach(c=>c.classList.remove('playing'))}
function clear(){pattern=pattern.map(r=>r.map(()=>0));refresh()}function magic(){pattern=pattern.map((r,ri)=>r.map(()=>Math.random()<[.45,.28,.22,.25,.15][ri]?1:0));refresh()}function recipe(x){clear();if(x==='dino'){pattern[0]=[1,0,0,0,1,0,0,0];pattern[1]=[0,0,1,0,0,0,1,0];pattern[4]=[0,0,0,0,1,0,0,0]}if(x==='snake'){pattern[1]=[1,0,1,0,1,0,1,0];pattern[3]=[0,1,0,1,0,1,0,1]}if(x==='cat'){pattern[0]=[1,0,0,1,1,0,0,1];pattern[2]=[0,1,0,0,0,1,0,0]}if(x==='space'){pattern[3]=[1,0,0,1,0,1,0,0];pattern[4]=[0,0,1,0,0,0,1,0]}refresh()}
render();document.addEventListener('click',e=>{let p=e.target.closest('[data-pad]');if(p)sound(p.dataset.pad);let c=e.target.closest('.cell');if(c){pattern[c.dataset.r][c.dataset.s]^=1;c.classList.toggle('on')}let r=e.target.closest('[data-recipe]');if(r)recipe(r.dataset.recipe)});playBtn.onclick=()=>playing?stop():play();stopBtn.onclick=stop;clearBtn.onclick=clear;randomBtn.onclick=magic;['bpm','pitch','echo','fuzz','space','swing'].forEach(k=>$('#'+k).oninput=()=>{$('#'+k+'Out').textContent=$('#'+k).value;settings()});
